---
title: "WorldData2023: Descriptive analysis"
author: "Alberto and Ignacio"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Including the data

```{r}
library(readxl)
DataSet <- read_excel("WorldData_whole.xlsx")
#View(DataSet)
GDP = DataSet$GDP
```

#Initial check of the data: In order to see if the data is valid to study the reasons why a playlist is the first one in spotify we'll look at the data of the playlist chosen for the year 2000.

##Create the frequency and relative frequency tables for the data

```{r}
DataSet$GDP = log10(DataSet$GDP)
DataSet$Population = log10(DataSet$Population)
DataSet$Urban_population = log10(DataSet$Urban_population)
DataSet$`Land Area(Km2)` = log10(DataSet$`Land Area(Km2)`)
DataSet$`Co2-Emissions` = log10(DataSet$`Co2-Emissions`)
DataSet$`Armed Forces size` = log10(DataSet$`Armed Forces size`)

GDP = DataSet$GDP

#Check the popularity of the tracks in that year
#ABStable <- table(GDP)
#RELtable <- prop.table(ABStable)
#ABStable
#RELtable

```

```{r}
library(ggplot2)
suppressWarnings(library(ggplot2))
for (name in names(DataSet)) {
  if (name != "Armed Forces size"){
    variable <- DataSet[[name]]
    FPlot <- ggplot(DataSet, aes(x = variable)) +
      geom_histogram(alpha = 0.7, fill = "darkgreen", color = "black") +
      geom_boxplot(alpha = 0.9, fill = "green", color = "black") +
      labs(title = sprintf("Distribution of %s", name), x = sprintf("%s", name), y = "Frequency")
    
    print(FPlot)
  }
    
  }


```
```{r}
#NDataSet = DataSet[Popularity >50,]
NDataSet = DataSet
for (name in names(NDataSet)) {
   if (name != "Armed Forces size"){
    variable = NDataSet[[name]]
    SPlot = plot(GDP,variable, xlab = "GDP", ylab = sprintf("%s", name))
    print(SPlot)
  
    RegressionModel <- lm(GDP ~ variable, data=NDataSet)
    abline(RegressionModel)
   }
  }

```

```{r}
#cov(NDataSet$track_popularity, NDataSet$energy)
#cov(NDataSet)
#cor(NDataSet$track_popularity, NDataSet$energy)
DataSet$`Armed Forces size` = NULL
cor(DataSet,use = "complete.obs")
```



```{r}
#View(NDataSet)
for (name in names(NDataSet)) {
    variable = NDataSet[[name]]
    RegressionModel <- lm(GDP ~ variable, data=NDataSet) 
    par(mfrow=c(2,2)) 
    plot(RegressionModel)    
  }

```

