% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Diagnosis of the model - Goodness of fit tests},
  pdfauthor={Bachelor in Computer Science and Engineering},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{\textbf{Diagnosis of the model - Goodness of fit tests}}
\author{Bachelor in Computer Science and Engineering}
\date{2020/21}

\begin{document}
\maketitle

\hypertarget{introduction}{%
\section{1. Introduction}\label{introduction}}

The aim of this practice is to assign a probability model to a sample
dataset in such a way that the chosen model can represent the population
from which the data was taken. The task of looking for the suitable
model is denoted by \textbf{distribution fitting}. In order to select a
good probability model for a given dataset it is necessary to make
statistical tests. The task to execute these tests is called
\textbf{diagnosis of the model}. Therefore we will say that a model
\textbf{fits well} the data if our data sample will positively pass the
tests of the \textbf{diagnosis}.

The usual way to perform the distribution fitting is the following. We
start from a data sample and we compare its empirical distribution with
the one of known models (Normal, Poisson, Exponential, etc). To evaluate
the goodness-of-fit of a model we will make the Chi-squared test.

In the following we will use the data contained in the file
\texttt{TiempoaccesoWeb.xlsx}. We start by analyzing the variable
\texttt{Ordenador\_Uni} in the file \texttt{TiempoAccesoWeb.xlsx}. This
variable contains 55 measurements of times, measured in seconds, that
are the times needed to access to the University UC3M's web page from a
computer of its library. Starting from this set of data, we want to find
a probability model that well describes the population of the accessing
times necessary to access from a computer of the library the web page of
the University UC3M. Afterwards we analyze the variable \texttt{tiempo}
of the file \texttt{AlumnosIndustriales.xlsx} that contains measurements
of the time spent by a group of students to get to the University.

\hypertarget{model-fitting.-variable-ordenador_uni}{%
\section{\texorpdfstring{2. Model fitting. Variable
\texttt{Ordenador\_Uni}}{2. Model fitting. Variable Ordenador\_Uni}}\label{model-fitting.-variable-ordenador_uni}}

\hypertarget{descriptive-analysis-of-the-data}{%
\subsection{2.1 Descriptive analysis of the
data}\label{descriptive-analysis-of-the-data}}

The first thing to do is the descriptive analysis of the data (computing
the characteristic measures and inspecting the histogram). In this way
we could have a first idea of which model to use.

First we read and view the data file. The figure shows the first five
observations of this datafile. Note that the line
\texttt{View(TiempoAccesoWeb)} appears as a comment, to execute it,
simply delete the symbol \texttt{\#}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}
\NormalTok{TiempoAccesoWeb }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"TiempoAccesoWeb.xlsx"}\NormalTok{)}
\CommentTok{\#View(TiempoAccesoWeb)}
\end{Highlighting}
\end{Shaded}

\includegraphics{TiempoAccesoWeb.jpg}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{library}\NormalTok{(summarytools))}
\FunctionTok{descr}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Descriptive Statistics  
## TiempoAccesoWeb$Ordenador_Uni  
## N: 55  
## 
##                     Ordenador_Uni
## ----------------- ---------------
##              Mean            1.42
##           Std.Dev            0.13
##               Min            1.16
##                Q1            1.34
##            Median            1.42
##                Q3            1.50
##               Max            1.68
##               MAD            0.11
##               IQR            0.15
##                CV            0.09
##          Skewness            0.08
##       SE.Skewness            0.32
##          Kurtosis           -0.47
##           N.Valid           55.00
##         Pct.Valid          100.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni, }
     \AttributeTok{probability =} \ConstantTok{TRUE}\NormalTok{, }\CommentTok{\# histogram has a total area = 1}
     \AttributeTok{xlab =} \StringTok{"Ordenador\_Uni"}\NormalTok{) }
\FunctionTok{curve}\NormalTok{(}\FunctionTok{dnorm}\NormalTok{(x, }\FunctionTok{mean}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni), }\FunctionTok{sd}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni)), }
      \AttributeTok{col=}\StringTok{"blue"}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{add=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{yaxt=}\StringTok{"n"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Goodness_of_fit_files/figure-latex/unnamed-chunk-2-1.pdf}

We can appreciate that the histogram looks like a Normal density
function. Indeed it is unimodal and quite symmetric
(\texttt{Skewness\ =\ 0.08}) but its bell is not exactly like the Gauss'
one (\texttt{Kurtosis\ =\ -0.29}). From this we can deduce that a normal
distribution could fit well our data and so it could be a good model for
the population we are studying.

\hypertarget{diagnosis-of-the-chosen-model}{%
\subsection{2.2 Diagnosis of the chosen
model}\label{diagnosis-of-the-chosen-model}}

To evaluate the goodness of the fitted model we can use the Chi-squared
test. We should remember that the Chi-squared test is a discrepancy
measure among the observed and expected number of observations in a
given partition

\[\sum_{i=1}^{k} \frac{(O_i-E_i)^2}{E_i},\]

where \(k\) is the number of intervals or cells in the partition,
\(O_i\) is the number of observations that are in \(i\)-th cell and
\(E_i\) is the expected number of observations in the same cell.

First, we must construct a partition of \(\mathbb{R}\) and count how
many values of \texttt{Ordenador\_Uni} fall in each interval of the
partition. An easy way is to use the partition obtained by the
\texttt{hist} function

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Partition }\OtherTok{\textless{}{-}} \FunctionTok{hist}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni, }\AttributeTok{plot =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{Partition}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
## [1] 1.1 1.2 1.3 1.4 1.5 1.6 1.7
## 
## $counts
## [1]  2  7 13 20  7  6
## 
## $density
## [1] 0.3636364 1.2727273 2.3636364 3.6363636 1.2727273 1.0909091
## 
## $mids
## [1] 1.15 1.25 1.35 1.45 1.55 1.65
## 
## $xname
## [1] "TiempoAccesoWeb$Ordenador_Uni"
## 
## $equidist
## [1] TRUE
## 
## attr(,"class")
## [1] "histogram"
\end{verbatim}

The component \texttt{breaks} of \texttt{Partition} gives the points
that define the intervals in the histogram. That is, the six intervals
in the partition are \((1.1, 1.2]\), \((1.2, 1.3]\), \((1.3, 1.4]\),
\((1.4, 1.5]\), \((1.5, 1.6]\) and \((1,6, 1.7]\). The component
\texttt{counts} gives the number of observations inside each interval or
cell. This are the \textbf{observed}, \(O_i\).

It should be noted that the above partition does not cover all
\(\mathbb{R}\) since intervals \((-\infty, 1.1]\) and \((1.7, +\infty)\)
are not considered. We will assume that the first interval of the
partition is \((-\infty, 1.2]\) and the last interval is
\((1.6, +\infty)\).

Next, we fit the normal model to \texttt{Ordenador\_Uni}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(fitdistrplus)}
\NormalTok{normalfit }\OtherTok{\textless{}{-}} \FunctionTok{fitdist}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni, }\StringTok{"norm"}\NormalTok{)}
\NormalTok{normalfit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Fitting of the distribution ' norm ' by maximum likelihood 
## Parameters:
##       estimate Std. Error
## mean 1.4248182 0.01670598
## sd   0.1238948 0.01180945
\end{verbatim}

The estimated parameters for the Normal random variable are in our case
\(\widehat{\mu} = 1.42481818\) and \(\widehat{\sigma} = 0.12389484\)
that are equal to the corresponding values shown in the descriptive
analysis of the variable. Therefore the fitted model is
\[X \sim \mathcal{N}(1.42481818, 0.12389484).\]

Finally, we perform a diagnosis test to appreciate the goodness of our
fitting. We should calculate the expected number of observations under
the \emph{fitted} normal distribution

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CummulativeProbabilities }\OtherTok{=} \FunctionTok{pnorm}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\ConstantTok{Inf}\NormalTok{, Partition}\SpecialCharTok{$}\NormalTok{breaks[}\FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{,}\SpecialCharTok{{-}}\DecValTok{7}\NormalTok{)], }\ConstantTok{Inf}\NormalTok{),  }
\NormalTok{                      normalfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{1}\NormalTok{], normalfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{2}\NormalTok{])}
\NormalTok{Probabilities }\OtherTok{=} \FunctionTok{diff}\NormalTok{(CummulativeProbabilities)}
\NormalTok{Expected }\OtherTok{=} \FunctionTok{length}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni)}\SpecialCharTok{*}\NormalTok{Probabilities}
\FunctionTok{chisq.test}\NormalTok{(Partition}\SpecialCharTok{$}\NormalTok{counts, }\AttributeTok{p =}\NormalTok{ Probabilities)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in chisq.test(Partition$counts, p = Probabilities): Chi-squared
## approximation may be incorrect
\end{verbatim}

\begin{verbatim}
## 
##  Chi-squared test for given probabilities
## 
## data:  Partition$counts
## X-squared = 2.625, df = 5, p-value = 0.7576
\end{verbatim}

The result of the Chi-squared test can be resumed in the following three
quantities

\begin{itemize}
\tightlist
\item
  The calculated test statistic, \texttt{X-squared}
  \(= \sum_{i=1}^{k} \frac{(o_i-e_i)^2}{e_i}\), where \(o_i\) is the
  number of observations in the sample that are in \(i\)-th cell and
  \(e_i\) is the expected number of observations in the same cell.
\end{itemize}

\begin{quote}
This statistic summarizes the relation between the histogram and the
continuous curve of the density function. The bigger is its value the
worse is the goodness of the fit of the chosen theoretical model.
\end{quote}

\begin{itemize}
\tightlist
\item
  \texttt{df} (degrees of freedom), represents the parameter of the
  selected Chi-squared distribution and it is used as a reference point
  to appreciate the quality of the fitting.
\end{itemize}

\begin{quote}
\begin{itemize}
\tightlist
\item
  The degrees of freedom at the \texttt{chisq.test} function are
  computed as \texttt{df} \(= k - 1\) since it does not takes into
  account the number of estimated parameters.
\end{itemize}
\end{quote}

\begin{quote}
\begin{itemize}
\tightlist
\item
  The degrees of freedom must be computed as \texttt{df}
  \(= k - p - 1\), where \(p\) is the number of unknown parameters of
  the model that are estimated using the data sample, in this case it is
  equal to 2 (the mean and the variance).
\end{itemize}
\end{quote}

\begin{itemize}
\tightlist
\item
  \texttt{p-value} is the probability that the test statistic takes a
  value higher than \texttt{X-squared}. In this case it is given by the
  value of the area of the right-tail starting from 2.625 calculated
  with the density function of a Chi-squared distribution with
  \texttt{df} degrees of freedom.
\end{itemize}

\begin{quote}
\begin{itemize}
\tightlist
\item
  Notice that \texttt{df\ =\ 5} corresponds to number of cells minus
  one, \(k-1\), but we estimate two parameters, so we should to use a
  \(\chi^2\) distribution with \texttt{df\ =\ 3}, \(k - p - 1\).
\end{itemize}
\end{quote}

\begin{quote}
\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pchisq}\NormalTok{(}\FloatTok{2.5646}\NormalTok{, }\DecValTok{3}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4637294
\end{verbatim}
\end{quote}

\begin{quote}
That is, the correct \texttt{p-value} \(= 0.4637294\).
\end{quote}

If the \texttt{p-value} is less than 0.05 we assume that it is quite
improbable to obtain the resulting value of the test statistic if the
model were good. Therefore we conclude that the test is unsatisfactory.
On the other hand if the \texttt{p-value} is bigger than 0.05 we
conclude that the fit is relatively good and that the chosen model can
be considered reasonable to represent the population.

In our case the pvalue is equal to 0.4637294 and therefore we conclude
that the normal model is a reasonable model to represent our population.

\hypertarget{other-normality-goodness-of-fit-tests}{%
\subsection{2.3 Other normality goodness-of-fit
tests}\label{other-normality-goodness-of-fit-tests}}

The chi-square test is usually not recommended for testing the
hypothesis of normality due to its inferior power properties compared to
other tests. There are many functions in \textsf{R} to make various
different goodness-of-fit tests. All of them may be interpreted by
looking at the p-values in the same way we have done by looking at the
Chi-squared test. In particular, the package \texttt{nortest} includes
the following:

\begin{itemize}
\tightlist
\item
  \texttt{ad.test}: Anderson-Darling test
\item
  \texttt{cvm.test}: Cramer-von Mises test
\item
  \texttt{lillie.test}: Kolmogorov-Smirnov-Lilliefors test
\item
  \texttt{pearson.test}: Pearson chi-square test for normality
\item
  \texttt{sf.test}: Shapiro-Francia test
\end{itemize}

For example, it is possible to check that the p-values corresponding to
these tests are bigger than 0.05 too, thus corroborating our selection
of the Normal model.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(nortest)}
\FunctionTok{ad.test}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Anderson-Darling normality test
## 
## data:  TiempoAccesoWeb$Ordenador_Uni
## A = 0.4312, p-value = 0.2958
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cvm.test}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Cramer-von Mises normality test
## 
## data:  TiempoAccesoWeb$Ordenador_Uni
## W = 0.073781, p-value = 0.2447
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{lillie.test}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  TiempoAccesoWeb$Ordenador_Uni
## D = 0.088043, p-value = 0.3582
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pearson.test}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson chi-square normality test
## 
## data:  TiempoAccesoWeb$Ordenador_Uni
## P = 5.9091, p-value = 0.5504
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sf.test}\NormalTok{(TiempoAccesoWeb}\SpecialCharTok{$}\NormalTok{Ordenador\_Uni)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Francia normality test
## 
## data:  TiempoAccesoWeb$Ordenador_Uni
## W = 0.98159, p-value = 0.4749
\end{verbatim}

\vspace{0.5cm}

Also, it is possible to obtain a graphical representation of the fitting
by

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(normalfit)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Goodness_of_fit_files/figure-latex/unnamed-chunk-8-1.pdf}

\hypertarget{model-fitting-for-the-variable-tiempo}{%
\section{\texorpdfstring{3. Model fitting for the variable
\texttt{tiempo}}{3. Model fitting for the variable tiempo}}\label{model-fitting-for-the-variable-tiempo}}

In this section we repeat the above analysis for the variable
\texttt{tiempo} at file \texttt{AlumnosIndustriales.xlsx}. This variable
contains measurements of the time spent by a group of students to get to
the University. The sample size is equal to 95.

\hypertarget{descriptive-analysis-of-data}{%
\subsection{3.1 Descriptive analysis of
data}\label{descriptive-analysis-of-data}}

After loading the file \texttt{AlumnosIndustriales.xlsx}, we perform the
descriptive analysis of the variable \texttt{tiempo} (computing the
characteristic measures and inspecting the histogram).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{library}\NormalTok{(summarytools))}
\FunctionTok{descr}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Descriptive Statistics  
## AlumnosIndustriales$tiempo  
## N: 95  
## 
##                     tiempo
## ----------------- --------
##              Mean    41.42
##           Std.Dev    24.74
##               Min     1.00
##                Q1    20.00
##            Median    40.00
##                Q3    60.00
##               Max   120.00
##               MAD    29.65
##               IQR    40.00
##                CV     0.60
##          Skewness     0.63
##       SE.Skewness     0.25
##          Kurtosis    -0.04
##           N.Valid    95.00
##         Pct.Valid   100.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo, }
     \AttributeTok{probability =} \ConstantTok{TRUE}\NormalTok{, }\CommentTok{\# histogram has a total area = 1}
     \AttributeTok{xlab =} \StringTok{"Tiempo"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Goodness_of_fit_files/figure-latex/unnamed-chunk-10-1.pdf}

The data looks unimodal and with positive asymmetry. We have two options
to fit a model to these data. First we try to fit a model that has
positive asymmetry, like for example the Weibull distribution or the
Lognormal distribution. Next we will try to make a transformation of the
data in order to correct the asymmetry and to try to fit a Normal
distribution. For example, we could try to apply a square root operation
(note that to fit a Normal to the logarithm of a variable is the same as
to fit a Lognormal distribution to the variable with no transformation).

\hypertarget{fitting-a-weibull-distribution}{%
\subsection{3.2 Fitting a Weibull
distribution}\label{fitting-a-weibull-distribution}}

As in the previous example, we fit the model

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(fitdistrplus)}
\NormalTok{weibullfit }\OtherTok{\textless{}{-}} \FunctionTok{fitdist}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo, }\StringTok{"weibull"}\NormalTok{)}
\NormalTok{weibullfit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Fitting of the distribution ' weibull ' by maximum likelihood 
## Parameters:
##        estimate Std. Error
## shape  1.708639  0.1393375
## scale 46.341096  2.9242429
\end{verbatim}

Now, we will obtain the observed and the expected number of observations
in the intervals defined by the default histogram.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Partition }\OtherTok{\textless{}{-}} \FunctionTok{hist}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo, }\AttributeTok{plot =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{Partition}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
## [1]   0  20  40  60  80 100 120
## 
## $counts
## [1] 27 24 29  9  5  1
## 
## $density
## [1] 0.0142105263 0.0126315789 0.0152631579 0.0047368421 0.0026315789
## [6] 0.0005263158
## 
## $mids
## [1]  10  30  50  70  90 110
## 
## $xname
## [1] "AlumnosIndustriales$tiempo"
## 
## $equidist
## [1] TRUE
## 
## attr(,"class")
## [1] "histogram"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CummulativeProbabilities }\OtherTok{=} \FunctionTok{pweibull}\NormalTok{(}\FunctionTok{c}\NormalTok{(Partition}\SpecialCharTok{$}\NormalTok{breaks[}\SpecialCharTok{{-}}\DecValTok{7}\NormalTok{], }\ConstantTok{Inf}\NormalTok{),  }
\NormalTok{                      weibullfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{1}\NormalTok{], weibullfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{2}\NormalTok{])}
\NormalTok{Probabilities }\OtherTok{=} \FunctionTok{diff}\NormalTok{(CummulativeProbabilities)}
\NormalTok{Expected }\OtherTok{=} \FunctionTok{length}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo)}\SpecialCharTok{*}\NormalTok{Probabilities}
\FunctionTok{chisq.test}\NormalTok{(Partition}\SpecialCharTok{$}\NormalTok{counts, }\AttributeTok{p =}\NormalTok{ Probabilities)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in chisq.test(Partition$counts, p = Probabilities): Chi-squared
## approximation may be incorrect
\end{verbatim}

\begin{verbatim}
## 
##  Chi-squared test for given probabilities
## 
## data:  Partition$counts
## X-squared = 7.0387, df = 5, p-value = 0.2178
\end{verbatim}

Here, again, we should to re-calculate the \texttt{p-value}since we
estimate the two parameters of the Weibull distribution.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pchisq}\NormalTok{(}\FloatTok{7.0467}\NormalTok{, }\DecValTok{3}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.07042409
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(weibullfit)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Goodness_of_fit_files/figure-latex/unnamed-chunk-15-1.pdf}

From a comparison of histogram with the Weibull density function and
from looking at the p-value we realize that the fit is satisfactory.
This means that we could use the Weibull probability model to describe
the time spent by the students to get to the University.

\hypertarget{fitting-a-lognormal-distribution}{%
\subsection{3.3 Fitting a Lognormal
distribution}\label{fitting-a-lognormal-distribution}}

We proceed as before: (i) model fitting; (ii) calculation of the
observed and expected number of observations at each interval in the
histogram and (iii) Chi-squared test.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(fitdistrplus)}
\NormalTok{lognormalfit }\OtherTok{\textless{}{-}} \FunctionTok{fitdist}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo, }\StringTok{"lnorm"}\NormalTok{)}
\NormalTok{lognormalfit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Fitting of the distribution ' lnorm ' by maximum likelihood 
## Parameters:
##          estimate Std. Error
## meanlog 3.4891976 0.08090337
## sdlog   0.7885485 0.05720691
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Partition }\OtherTok{\textless{}{-}} \FunctionTok{hist}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo, }\AttributeTok{plot =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{Partition}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
## [1]   0  20  40  60  80 100 120
## 
## $counts
## [1] 27 24 29  9  5  1
## 
## $density
## [1] 0.0142105263 0.0126315789 0.0152631579 0.0047368421 0.0026315789
## [6] 0.0005263158
## 
## $mids
## [1]  10  30  50  70  90 110
## 
## $xname
## [1] "AlumnosIndustriales$tiempo"
## 
## $equidist
## [1] TRUE
## 
## attr(,"class")
## [1] "histogram"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CummulativeProbabilities }\OtherTok{=} \FunctionTok{plnorm}\NormalTok{(}\FunctionTok{c}\NormalTok{(Partition}\SpecialCharTok{$}\NormalTok{breaks[}\SpecialCharTok{{-}}\DecValTok{7}\NormalTok{], }\ConstantTok{Inf}\NormalTok{),  }
\NormalTok{                      lognormalfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{1}\NormalTok{], lognormalfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{2}\NormalTok{])}
\NormalTok{Probabilities }\OtherTok{=} \FunctionTok{diff}\NormalTok{(CummulativeProbabilities)}
\NormalTok{Expected }\OtherTok{=} \FunctionTok{length}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo)}\SpecialCharTok{*}\NormalTok{Probabilities}
\FunctionTok{chisq.test}\NormalTok{(Partition}\SpecialCharTok{$}\NormalTok{counts, }\AttributeTok{p =}\NormalTok{ Probabilities)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Chi-squared test for given probabilities
## 
## data:  Partition$counts
## X-squared = 16.15, df = 5, p-value = 0.00643
\end{verbatim}

It looks clear that this fitting is no such good as the one before. The
p-value obtained by the Chi-squared test is very low. In fact, the
\texttt{p-value} is smaller since we should use
\texttt{pchisq(16.15,\ 3,\ lower.tail\ =\ FALSE)}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(lognormalfit)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Goodness_of_fit_files/figure-latex/unnamed-chunk-17-1.pdf}

The histogram gives us the reason of the bad fit; indeed the Lognormal
distribution has a higher kurtosis than the dataset. In conclusion the
Lognormal model is not good to represent our data.

\hypertarget{fitting-a-normal-distribution-to-a-transformation-of-the-dataset}{%
\subsection{3.4 Fitting a Normal distribution to a transformation of the
dataset}\label{fitting-a-normal-distribution-to-a-transformation-of-the-dataset}}

The variable \texttt{tiempo} is positive asymmetric, however its
square-root looks quite symmetric. If we fit a Normal distribution to
the square-root of the data we get the following results:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(fitdistrplus)}
\NormalTok{normalfit }\OtherTok{\textless{}{-}} \FunctionTok{fitdistr}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo), }\StringTok{"normal"}\NormalTok{)}
\NormalTok{normalfit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      mean         sd    
##   6.1169314   2.0010506 
##  (0.2053035) (0.1451715)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Partition }\OtherTok{\textless{}{-}} \FunctionTok{hist}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo), }\AttributeTok{plot =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{Partition}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $breaks
##  [1]  1  2  3  4  5  6  7  8  9 10 11
## 
## $counts
##  [1]  2  2 15 11 15 17 18  9  5  1
## 
## $density
##  [1] 0.02105263 0.02105263 0.15789474 0.11578947 0.15789474 0.17894737
##  [7] 0.18947368 0.09473684 0.05263158 0.01052632
## 
## $mids
##  [1]  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5
## 
## $xname
## [1] "sqrt(AlumnosIndustriales$tiempo)"
## 
## $equidist
## [1] TRUE
## 
## attr(,"class")
## [1] "histogram"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{CummulativeProbabilities }\OtherTok{=} \FunctionTok{pnorm}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\ConstantTok{Inf}\NormalTok{, Partition}\SpecialCharTok{$}\NormalTok{breaks[}\FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{,}\SpecialCharTok{{-}}\DecValTok{11}\NormalTok{)], }\ConstantTok{Inf}\NormalTok{),  }
\NormalTok{                      normalfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{1}\NormalTok{], normalfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{2}\NormalTok{])}
\NormalTok{Probabilities }\OtherTok{=} \FunctionTok{diff}\NormalTok{(CummulativeProbabilities)}
\NormalTok{Expected }\OtherTok{=} \FunctionTok{length}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo)}\SpecialCharTok{*}\NormalTok{Probabilities}
\FunctionTok{chisq.test}\NormalTok{(Partition}\SpecialCharTok{$}\NormalTok{counts, }\AttributeTok{p =}\NormalTok{ Probabilities)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Chi-squared test for given probabilities
## 
## data:  Partition$counts
## X-squared = 9.3823, df = 9, p-value = 0.4028
\end{verbatim}

The \texttt{p-value} taking into account that two parameters were
estimated is

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pchisq}\NormalTok{(}\FloatTok{9.3823}\NormalTok{, }\DecValTok{7}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.226361
\end{verbatim}

which is bigger than 0.05.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo), }
          \AttributeTok{probability =} \ConstantTok{TRUE}\NormalTok{, }\CommentTok{\# histogram has a total area = 1}
     \AttributeTok{xlab =} \StringTok{"Tiempo"}\NormalTok{, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\FloatTok{0.2}\NormalTok{))}
\FunctionTok{curve}\NormalTok{(}\FunctionTok{dnorm}\NormalTok{(x, normalfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{1}\NormalTok{], normalfit}\SpecialCharTok{$}\NormalTok{estimate[}\DecValTok{2}\NormalTok{]), }
      \AttributeTok{col=}\StringTok{"blue"}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{, }\AttributeTok{add=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{yaxt=}\StringTok{"n"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Goodness_of_fit_files/figure-latex/unnamed-chunk-20-1.pdf}

The fitting looks almost as good as the one done by using the Weibull
distribution.

We can check the above results by the normality tests mentioned in
section 2.3:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(nortest)}
\FunctionTok{ad.test}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Anderson-Darling normality test
## 
## data:  sqrt(AlumnosIndustriales$tiempo)
## A = 0.52436, p-value = 0.1773
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cvm.test}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Cramer-von Mises normality test
## 
## data:  sqrt(AlumnosIndustriales$tiempo)
## W = 0.086902, p-value = 0.1664
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{lillie.test}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  sqrt(AlumnosIndustriales$tiempo)
## D = 0.078749, p-value = 0.1562
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pearson.test}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo), }\AttributeTok{n.classes =} \DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson chi-square normality test
## 
## data:  sqrt(AlumnosIndustriales$tiempo)
## P = 10.368, p-value = 0.1686
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sf.test}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Francia normality test
## 
## data:  sqrt(AlumnosIndustriales$tiempo)
## W = 0.98791, p-value = 0.458
\end{verbatim}

\hypertarget{example-of-an-application-of-the-goodness-of-fit-test}{%
\section{4. Example of an application of the goodness-of-fit
test}\label{example-of-an-application-of-the-goodness-of-fit-test}}

To have a good model that represents the population from which we may
have obtained a data sample is very useful. It allows, among other
things, to compute the probabilities of events in a way much more
precise than using the observed relative frequencies of the sample
dataset.

In this example we compute the probability that a student lives at a
distance of more than one hour from the University. We can do this by
using the Weibull model as well as by using the Normal model applied to
the square root of the variable \texttt{tiempo}. These two models will
give us two different results, however we expect them to be very close
to each other.

\hypertarget{computation-using-the-weibull-model}{%
\subsection{4.1 Computation using the Weibull
model}\label{computation-using-the-weibull-model}}

As we have seen above, the Weibull that better fits our data has the
following parameters: \texttt{shape} = 1.7088275 and \texttt{scale} =
46.3508101. Then, we can calculate the required probability,
\(\Pr(Tiempo > 60)\), by

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pweibull}\NormalTok{(}\DecValTok{60}\NormalTok{, }\AttributeTok{shape =} \FloatTok{1.7088275}\NormalTok{, }\AttributeTok{scale =} \FloatTok{46.3508101}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2113264
\end{verbatim}

We can conclude that the probability that a student lives at a distance
of more than one hour from the University is approximately equal to
0.211.

\hypertarget{computation-using-the-normal-model-applied-to-the-square-root-of-the-variable}{%
\section{4.2 Computation using the Normal model applied to the
square-root of the
variable}\label{computation-using-the-normal-model-applied-to-the-square-root-of-the-variable}}

As seen above, the square root can be well fitted to a Normal
distribution. To compute the probability that the student takes more
than 60 minutes to get at the University it is equivalent to compute the
probability that the square root of the spent time is more than
\(\sqrt(60) = 7.745967\) (measured as square-root of minutes). The
Normal distribution that better fits our data has the following
estimated parameters: \texttt{mean} = 6.1169314 and \texttt{sd} =
2.0010506.

We can then compute the required probability for this distribution by

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pnorm}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{60}\NormalTok{), }\AttributeTok{mean =} \FloatTok{6.1169314}\NormalTok{, }\AttributeTok{sd =} \FloatTok{2.0010506}\NormalTok{, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2077967
\end{verbatim}

Therefore, by using this model, the probability that a student lives at
a distance of more than one hour from the University is approximately
equal to 0.208, and it is very close to the computed by using the
Weibull model.

The following graph provides a comparison of the estimated distribution
function using the Weibull model (in red) and the Normal model (in
blue). It is clear that both models are very similar, and reasonably fit
the empirical distribution function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{ecdf}\NormalTok{(AlumnosIndustriales}\SpecialCharTok{$}\NormalTok{tiempo))}
\FunctionTok{lines}\NormalTok{(}\DecValTok{0}\SpecialCharTok{:}\DecValTok{130}\NormalTok{, }\FunctionTok{pweibull}\NormalTok{(}\DecValTok{0}\SpecialCharTok{:}\DecValTok{130}\NormalTok{, }\AttributeTok{shape =} \FloatTok{1.7088275}\NormalTok{, }\AttributeTok{scale =} \FloatTok{46.3508101}\NormalTok{), }\AttributeTok{col=}\StringTok{"red"}\NormalTok{) }
\FunctionTok{lines}\NormalTok{(}\DecValTok{0}\SpecialCharTok{:}\DecValTok{130}\NormalTok{, }\FunctionTok{pnorm}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{0}\SpecialCharTok{:}\DecValTok{130}\NormalTok{),  }\AttributeTok{mean =} \FloatTok{6.1169314}\NormalTok{, }\AttributeTok{sd =} \FloatTok{2.0010506}\NormalTok{), }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Goodness_of_fit_files/figure-latex/unnamed-chunk-24-1.pdf}

\end{document}
